### ISSUE TITLE
404 Not Found The requested URL was not found Raspberry

### ISSUE THREAD

**Issue by mrsero** [opalenzuela/opendomo#106]
Hola he instalado la version 2.1.0 pero no consigo entrar a la interface web.
me da el siguiente error 

404 Not Found
The requested URL was not found 

Puedo conectar,e por ssh sin problemas y el puerto http esta a la escucha

netstat -l | grep http

tcp6       0      0 [::]:http               [::]:*                  LISTEN

Este es el http.conf

A:127.0.0.1
A:192.168.
I:index.html
*.pl:/usr/bin/perl
*.py:/usr/bin/python
*.sh:/bin/sh
/cgi-bin/admin:admin:opendomo
/admin:admin:opendomo
/user:user:opendomo

tambien probe entrar con esta ruta sin resultado 

ip.rs.pi//advanced.html

si reinicio el servicio me da el siguiente error

 service httpd restart
[ ok ] Stoping HTTPD busybox server...done.
[....] Starting HTTPD busybox server...httpd: chdir(/var/www): No such file or directory
failed.

alguna idea 
saludos gracias

**Comment by opalenzuela** [comment]
Queda corregido con la siguiente versión. Cerramos issue.

**Comment by opalenzuela** [comment]
Explicación de la solución en el issue #123
