### ISSUE TITLE
Missing all-all eventhandler

### ISSUE THREAD

**Issue by opalenzuela** [opalenzuela/opendomo#112]
The base system must have the basic eventhandler pre-configured: 

There should be a symbolic link to the file  **/usr/local/opendomo/eventhandlers/writeToLog.sh** in **/etc/opendomo/eventhandlers/** with the name **all-all**

**Comment by jmirasb** [comment]
Yes, configuration manager didn't copy symbolic links. I think is fixed in last commit

**Comment by opalenzuela** [comment]
Solved and verified.
