### ISSUE TITLE
Add system state "idle"

### ISSUE THREAD

**Issue by opalenzuela** [opalenzuela/opendomo#113]
It would be interesting to have a system state where all the daemons are disabled. This would be useful, for instance, when several computers with OpenDomoOS are running in the same network and we don't want them to compete for resources.

This state will have the particularity that it cannot be edited, but it can be shown. Not sure if it should be shown to the user or only internally.

**Comment by jmirasb** [comment]
I add idle state. For now, this state is hidden in all states scripts. So, can be configured or activated by user.
