### ISSUE TITLE
Ayuda Raspberry B+

### ISSUE THREAD

**Issue by valverdeJA** [opalenzuela/opendomo#120]
Muy buenas, he visto que estáis buscando ayuda por falta de una Raspberry B+.

Yo tengo una y me interesa este tema.

¿En que puedo ayudar?

Mi twitter es:  @Valverde_ja 
Un saludo.

**Comment by opalenzuela** [comment]
Síguenos en el Issue #77 para poder hacer las pruebas sobre tu Raspberry PI B+. Allí tenemos una discusión iniciada.
