### ISSUE TITLE
Error 404 Running opendomoOS2.1 in virtualvox

### ISSUE THREAD

**Issue by aitorantonanzas** [opalenzuela/opendomo#123]
Me podeis confirmar si funciona correctamente opendomoOS2.1 en virtualvox?? no consigo hacerla funcionar.

Aparentemente todo funciona correctamente por que arranca sin fallos y obtiene una ip del dhcp pero cuando intento acceder a el por la web no aparece la pagina de login simepre me da error  404 Not Found The requested URL was not found

Configuro todo al pie de la letra como pone el manual pero nada.

Por otra parte el comando ifconfig me dice  command not found  y para ver la ip tengo que introducir ip addr para que me muestre la ip.

**Comment by aitorantonanzas** [comment]
con la ip de autoconfiguracion 169.254.0.25 tambien me pasa lo mismo.

**Comment by opalenzuela** [comment]
La descripción del problema se parece sospechosamente al #106. 
¿Podrías decirnos qué te sale en el directorio /var/www ?

**Comment by opalenzuela** [comment]
He encontrado el problema de ambos issues (un fallo con las dependencias de Debian) y una forma de solucionarlo. Para ello necesitaréis una terminal abierta con el usuario "root". Los comandos son los siguientes:

    wget http://es.opendomo.org/files/odcommon_2.1.1_i386.deb
    wget http://es.opendomo.org/files/odcgi_2.1.1_i386.deb
    apt-get install ntp
    dpkg -i odcommon*.deb
    dpkg -i odcgi*.deb

*Nota: Para Raspberry, hay que cambiar "i386" por "armhf".*

**Comment by aitorantonanzas** [comment]
Parece que todo los paquetes se instalan correctamente pero me sigue apareciendo el error 404.
Entiendo que con 2.1 me olvido del tema de la persistencia de datos... o tendria que crear un disco y montarlo como se indica aqui???
http://www.opendomo.com/wiki/index.php/Virtualizar_con_persistencia_de_datos
hablo desde virtualbox con la raspberry aun no lo e podido probar.

**Comment by aitorantonanzas** [comment]
Ma o menos cada 5 min con la maquina arrancada me lanza el siguiente mensaje " INIT: version 2.08 reloading" esto es normal?

**Comment by mrsero** [comment]
Hola 
Parece que no termina de arreglar
sigo todos los pasos sin problemas pero sigue saliendo el dichoso 404
intente reiniciar el servidor http pero no esta escuchando y no dio ningun error al arrancarlo


<pre><code>Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 *:ssh                   *:*                     LISTEN     
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN     
udp        0      0 *:bootpc                *:*                                
udp        0      0 192.168.1.25:ntp        *:*                                
udp        0      0 192.168.1.2:ntp         *:*                                
udp        0      0 OpenDomoOS:ntp          *:*                                
udp        0      0 *:ntp                   *:*                                
udp        0      0 *:44283                 *:*                                
udp6       0      0 [::]:38194              [::]:*                             
udp6       0      0 fe80::20c:29ff:fea1:ntp [::]:*                             
udp6       0      0 fd24:7ec1:9cc5:0:20:ntp [::]:*                             
udp6       0      0 ::1:ntp                 [::]:*                             
udp6       0      0 [::]:ntp                [::]:*                             
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     SEQPACKET  LISTENING     317      /run/udev/control
</code></pre>

**Comment by opalenzuela** [comment]
@aitorantonanzas no, a partir de la versión 2 ya no es necesario usar ese mecanismo, ya que se abandonó el sistema de ISO para usar directamente máquinas virtuales. Por tanto, el disco que montamos ya se usa para la persistencia.

@mrsero ¿Tienes algo en el directiorio /var/www ? ¿Existe? No entiendo como puedes tener un 404 si el servidor web no está levantado... ¿probaste de guardar cambios y reiniciar?

**Comment by mrsero** [comment]
Buenos días oriol 
Tras instalar los paquetes el servidor http esta levantado pero sigue apareciendo el error a si que reinicie el servidor y vi que no aparecía

**Comment by mrsero** [comment]
Buenos días oriol 
Tras instalar los paquetes el servidor http esta levantado pero sigue apareciendo el error a si que reinicie el servidor y vi que no aparecía

**Comment by opalenzuela** [comment]
¿Pero tienes archivos en /var/www ? Si no los tienes es que no se te han instalado los paquetes...

**Comment by mrsero** [comment]
Sobre la persistencia veo que las descargas se guardan pero los cambios que hago en el archivo /etc/network/interfaces no

**Comment by mrsero** [comment]
salida del comando ls

<pre><code>ls /var/www/
admin                 css              images               skins
advanced.html         en.license.html  index.html           themes
apple-touch-icon.png  es.license.html  index.lighttpd.html  user
cgi-bin               favicon.ico      scripts              wzconf


</pre></code>

**Comment by opalenzuela** [comment]
¿Probaste de reiniciar lighttpd?

**Comment by mrsero** [comment]
Ya funciona 
y ayer no prque????

**Comment by opalenzuela** [comment]
¿Has reiniciado? o tal vez ahora funciona porque ha terminado de instalar dependencias. En la 2.1 tarda mucho...

**Comment by mrsero** [comment]
a de ser esta descargando ahora adauto y odweather, se esta tomando su tiempo

**Comment by mrsero** [comment]
Una pregunta en esta direccion no tendria que estar la paqueteria de opendomo

http://es.opendomo.org/files/

aparece vacia y los plugins tras una hora no se instalan

**Comment by opalenzuela** [comment]
Debe indicarse la ruta completa, o de lo contrario aparece vacía. 

Cierro issue por estar solucionado en la nueva versión.
