### ISSUE TITLE
ajustar interfaz web opendomo2.2

### ISSUE THREAD

**Issue by mrsero** [opalenzuela/opendomo#125]
Hola 
he probado opendomo 2.2 con distintos navegadores y la interface mo se adapta del todo
si el navegador esta maximixado se mescla las barras con los botones de off on y no se ve bien
encambio si se reduce si que se ve bien

<a href="http://es.tinypic.com?ref=v2tshk" target="_blank"><img src="http://i59.tinypic.com/v2tshk.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by opalenzuela** [comment]
Tomamos nota para revisarlo de cara al próximo update automático.

Gracias por el feedback!

**Comment by opalenzuela** [comment]
@mrsero ¿Podrías decirnos qué versión de ODControl estás usando? No conseguimos reproducir el problema.

**Comment by mrsero** [comment]
Domino 1.1.5

**Comment by opalenzuela** [comment]
Ok, el problema puede estar en Domino o en el plugin de automatismos entonces. ¿Podrías pasarnos la salida del siguiente comando?

    wget http://192.168.1.??/lsc

**Comment by mrsero** [comment]
wget http://192.168.1.00/lsc
<pre><code>--2015-02-04 15:05:43--  http://192.168.1.00/lsc
Conectando con 192.168.1.00:80... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: no especificado [text/plain]
Grabando a: “lsc”

    [  <=>                                  ] 178          346B/s   en 0,5s    

2015-02-04 15:05:44 (346 B/s) - “lsc” guardado [178]
</pre></code>

**Comment by opalenzuela** [comment]
¿Puedes hacer un "cat lsc" ahora?  Lo que necesito ver es qué devuelve el Domino

**Comment by opalenzuela** [comment]
O abre directamente desde el navegador   http://192.168.1.00/lsc

**Comment by mrsero** [comment]
di002:DIM_:ON
di003:DIM_:ON
di005:DIM_:OFF
BoBlg:DOM_:OFF
LampC:DOM_:OFF
do008:DOM_:OFF
Decod:DOM_:OFF
ai000:AIM_:00253:+00000|00100
ai001:AIM_:00024:+00000|00100
DONE

**Comment by opalenzuela** [comment]
Ok, gracias. Con esto ya podremos intentar simular tu entorno. 

El problema está en los bindings del plugin Automation, así que en cuanto lo tengamos solucionado te debería actualizar él sólo.

**Comment by opalenzuela** [comment]
Cerramos issue por no corresponderse a este módulo
