### ISSUE TITLE
Opendomo 2.2 no ejecuta acción con ODControl versión (1.5.2)

### ISSUE THREAD

**Issue by JOSELUISPN** [opalenzuela/opendomo#136]
He creado acciones en el menú de Iniciar acción de Opendomo 2,2, con los puertos de ODControl versión 1.5.2. y temporizadores, al final de las acciones con un (Finish successfully), he guardado la acción con su respectivo nombre.

Luego en el menú iniciar acciones, en Acciones disponibles doy clic sobre una de ellas y me sale el mensaje Lanzando (acción 1), pero no ejecuta la acción físicamente no hay on/off en los puertos, he probado lo mismo en Opendomo 1.0 y funciona perfectamente con el mismo ODControl.

**Comment by opalenzuela** [comment]
Sobre el sistema configurado, podrías hacer la siguiente prueba?

Supongamos que tienes un puerto de salida llamado do001 en un ODControl llamado "odcontrol". Trata de activarlo desde la consola con el siguiente comando:

     # /var/opendomo/control/odcontrol/do001 on

¿Qué salida obtienes por pantalla? ¿Se activa el puerto?

**Comment by JOSELUISPN** [comment]
Hola
he intentado desde maquina virtual opendomo 2.2 # /var/opendomo/control/odctl/do001 on # /var/opendomo/control/192168145/SalaC on # /var/opendomo/control/ODControl/SalaC onhe realizado varios intentos con diferentes puertos, lo que no estoy seguro es de el nombre de mi dispositivo odcontrol, en opendomo lo reconoce con el nombre de la ip, tambien intente con este, pero no hay ningun resultado, no se activa el puerto, y por pantalla tampoco sale nada..

 



     El Lunes, 23 de marzo, 2015 5:09:54, Oriol Palenzuela <notifications@github.com> escribió:
   

 Sobre el sistema configurado, podrías hacer la siguiente prueba?Supongamos que tienes un puerto de salida llamado do001 en un ODControl llamado "odcontrol". Trata de activarlo desde la consola con el siguiente comando: # /var/opendomo/control/odcontrol/do001 on
¿Qué salida obtienes por pantalla? ¿Se activa el puerto?—

**Comment by JOSELUISPN** [comment]
nuevamente intente y si acciona desde consola....
 # /var/opendomo/control/192168145/SalaC on
probe con todos los puertos y si accionan, en la parte gràfica tambien si cambian de on a off
pero sigue aun sin lanzar las secuencias,,,q más tendría q hacer, para que funcione el lanzador de acciones...
 



     El Domingo, 29 de marzo, 2015 16:03:43, José Luis Peralta Nolasco <jos_epn@yahoo.com> escribió:
   

 Hola
he intentado desde maquina virtual opendomo 2.2 # /var/opendomo/control/odctl/do001 on # /var/opendomo/control/192168145/SalaC on # /var/opendomo/control/ODControl/SalaC onhe realizado varios intentos con diferentes puertos, lo que no estoy seguro es de el nombre de mi dispositivo odcontrol, en opendomo lo reconoce con el nombre de la ip, tambien intente con este, pero no hay ningun resultado, no se activa el puerto, y por pantalla tampoco sale nada..

 



     El Lunes, 23 de marzo, 2015 5:09:54, Oriol Palenzuela <notifications@github.com> escribió:
   

 Sobre el sistema configurado, podrías hacer la siguiente prueba?Supongamos que tienes un puerto de salida llamado do001 en un ODControl llamado "odcontrol". Trata de activarlo desde la consola con el siguiente comando: # /var/opendomo/control/odcontrol/do001 on
¿Qué salida obtienes por pantalla? ¿Se activa el puerto?—

**Comment by opalenzuela** [comment]
Sería interesante que intentaras ejecutar la acción directamente desde la línea de comandos. Para ello tendrías que hacer lo siguiente:

     # cd /etc/opendomo/actions/
     # sh {nombreaccion}

¿Obtienes alguna salida por pantalla?

**Comment by JOSELUISPN** [comment]
hola
dentro del directorio /etc/opendomo/actions/ejecute ls para ver el nombre de las acciones que tengo creadas q son de apagado de toda la iluminacion las mismas q se encuentran con el nombre de apagar, y apagar todo

y me muestra las accionesact1428280226.actionact1428278049.action
ejecute con #sh act1428278049.action
 
me sale lo siguiente.... en el modo gráfico no pasa nada y físicamente no existe apagado de los puertos
   


     El Lunes, 30 de marzo, 2015 3:32:14, Oriol Palenzuela <notifications@github.com> escribió:
   

 Sería interesante que intentaras ejecutar la acción directamente desde la línea de comandos. Para ello tendrías que hacer lo siguiente: # cd /etc/opendomo/actions/
 # sh {nombreaccion}
¿Obtienes alguna salida por pantalla?—

**Comment by JOSELUISPN** [comment]
me sale lo siguiente...

root@OpendomoOS:/etc/opendomo/actions# sh act1428278049.action
act1428278049.action: line3: setport.sh: command not found
act1428278049.action: line4: wait.sh: command not found
act1428278049.action: line5: setport.sh: command not found
act1428278049.action: line6: wait.sh: command not found
act1428278049.action: line7: setport.sh: command not found
act1428278049.action: line8: wait.sh: command not found
act1428278049.action: line9: setport.sh: command not found
act1428278049.action: line10: wait.sh: command not found
act1428278049.action: line11: setport.sh: command not found
act1428278049.action: line12: wait.sh: command not found

**Comment by opalenzuela** [comment]
Perfecto! El problema está localizado: se trata de la variable PATH, que en el momento de ejecutar el script no incluye una de las rutas necesarias.

**Comment by opalenzuela** [comment]
Lo acabo de comprobar y PATH está correctamente asignado en la versión 2.2. No te va a funcionar como usuario root, debes lanzar las acciones como usuario llano o admin (root no se usa en OpenDomoOS por razones de seguridad).

**Comment by JOSELUISPN** [comment]
si ingrese usuario admin, y clave. pero ahì me sale el siguiente mensaje:

cuando ejecuto....cd /etc/opendomo/actions/ su act1428267871.action
No passwd entry for user 'act1428267871.action'

ya intente antes esto... he intentado con usuario admin y clave, y tambien como superusuario, 

no funciona.. 



     El Martes, 7 de abril, 2015 3:17:56, Oriol Palenzuela <notifications@github.com> escribió:
   

 Lo acabo de comprobar y PATH está correctamente asignado en la versión 2.2. No te va a funcionar como usuario root, debes lanzar las acciones como usuario llano o admin (root no se usa en OpenDomoOS por razones de seguridad).—

**Comment by JOSELUISPN** [comment]
siempre he intentado como usuario normal... pero no pasa nada no se ejecutan las acciones 


     El Domingo, 12 de abril, 2015 19:48:38, José Luis Peralta Nolasco <jos_epn@yahoo.com> escribió:
   

 si ingrese usuario admin, y clave. pero ahì me sale el siguiente mensaje:

cuando ejecuto....cd /etc/opendomo/actions/ su act1428267871.action
No passwd entry for user 'act1428267871.action'

ya intente antes esto... he intentado con usuario admin y clave, y tambien como superusuario, 

no funciona.. 



     El Martes, 7 de abril, 2015 3:17:56, Oriol Palenzuela <notifications@github.com> escribió:
   

 Lo acabo de comprobar y PATH está correctamente asignado en la versión 2.2. No te va a funcionar como usuario root, debes lanzar las acciones como usuario llano o admin (root no se usa en OpenDomoOS por razones de seguridad).—

**Comment by opalenzuela** [comment]
Trata de hacer log-in como el usuario admin y ejecutar la acción directamente. No uses "su"  para estas pruebas.

**Comment by JOSELUISPN** [comment]
ya no estoy utilizando su, solo como usuario admin, pero OpenDomo 2.2 sigue sin ejecutar las acciones.

**Comment by JOSELUISPN** [comment]
que prueba más podría hacer, para que se ejecuten las acciones de OpenDomo 2,2 con ODControl versión 1.5.2

**Comment by JOSELUISPN** [comment]
cuando ejecuto....cd /etc/opendomo/actions/ sh act1428267871.action

# Port 192168145/Dorm1 set to off
etc/opendomo/eventhandlers/all-all: line 8: var/opendomo/log/events,log: permision denied
Waiting [1s] seconds
usr/local/opendomo/bin/setport.sh: line 16 /var/opendomo/control/192168145/Dorm2: No such file or directory

ES UNA RUTINA DE APAGADO DE LUCES,,, cuando ejecuto la acción con sh me sale lo anterior en todos los puertos....

**Comment by opalenzuela** [comment]
Según los errores mostrados se trata de un problema de permisos. Al ejecutar el comando la primera vez con "su", los archivos creados tienen permisos de root o no se han creado bien. Prueba a guardar configuración y reiniciar la máquina, tal vez esto sea la forma más fácil de solucionar los problemas.
