### ISSUE TITLE
ODNetwork compatibility

### ISSUE THREAD

**Issue by haitor** [opalenzuela/opendomo#93]
Me gustaria actualizar el OdNetwork,pero veo que la version 2.1 no esta optimizado para esta plataforma.  Teneis pensado sacar versiones para ese dispositivo?

**Comment by aitorantonanzas** [comment]
hatior !!! tu debes de ser del país vasco!! estamos por guipuzcoa un par de paisanos que estamos con el mismo tema actualizar un odnetwork e instalarlo en una rpib+ asi que espermos que nos den soluciones pronto!!!

**Comment by opalenzuela** [comment]
Cerrando issue.
